### PR TITLE
feat: support building with user prebuilt rootfs

### PR DESCRIPTION
**Pull request by prodeveloper0**
Support building with user prebuilt rootfs by setting .BoadConfig.mk `CONFIG_USE_PREBUILT_ROOTFS=y`

### CODE REVIEW

**Comment by genesislab-samuellee** [comment]
It can reduce build time of firmware by ignoring to build rootfs and its components. just compile kernel and uboot with prebuilt rootfs!

**Comment by prodeveloper0** [comment]
It can reduce build time of firmware by ignoring to build rootfs and its components. just compile kernel and uboot with prebuilt rootfs!

**Comment by luckfox-eng33** [comment]
It may cause the media library related to rk to be unusable.
 And the absence of corresponding prebuilt rootfs ,may cause more confusion for some novices.

 I might be inclined not to merge into the master branch.
 But thank you for wanting to contribute to our community.

**Comment by prodeveloper0** [comment]
@luckfox-eng33 yes. this is advanced user feature who does not want to use OEM toolkit.
if you worried about claim from some novices, need to notify this is advanced user feature and it caused some errors or fails how you build custom rootfs.

**Comment by peterwillcn** [comment]
Yes, I prefer using Alpine, please support custom rootfs. @luckfox-eng33 Strongly request merging support for Alpine or OpenWrt rootfs

**Comment by peterwillcn** [comment]
Yes, Ubuntu is too bulky, I would rather purchase rk3588 using ubuntu, I prefer using Alpine for rv1106 , please support custom rootfs. @luckfox-eng33 Strongly request merging support for Alpine or OpenWrt rootfs
https://github.com/LuckfoxTECH/luckfox-pico/pull/111

**Comment by peterwillcn** [comment]
「bug report」
Why is rootfs only 55m in capacity, it should be 7G in capacity?
image

**Comment by luckfox-eng33** [comment]
> 「bug report」RV1106_Luckfox_Pico_Ultra_W「错误报告」RV1106_Luckfox_Pico_Ultra_W Why is rootfs only 55m in capacity, it should be 7G in capacity?为什么rootfs容量只有55m，应该是7G容量？ image



> 「bug report」RV1106_Luckfox_Pico_Ultra_W Why is rootfs only 55m in capacity, it should be 7G in capacity? image

1. It seems that the root file system does not have a normally mounted partition. It can be restored through resize2fs. For specific operations, please refer to the related operations of buildroot.
2. If you need to return a product, you can contact your dealer and do not need to declare it here

**Comment by luckfox-eng33** [comment]
> @luckfox-eng33 yes. this is advanced user feature who does not want to use OEM toolkit. if you worried about claim from some novices, need to notify this is advanced user feature and it caused some errors or fails how you build custom rootfs.

We are conducting a careful evaluation and our FAE team is exhausted by too many questions.
Maybe we can create a new branch specifically for users who need to build rootfs separately, instead of merging it into the main line, what do you think?

**Comment by prodeveloper0** [comment]
@luckfox-eng33 it's okay. if you were worried about exhausting your team to answer to the questions, it's good to separate branch technical supporting and non-technical supporing branch.

**Pull request merged**
